/*
 You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */
package Practice;

import java.util.Scanner;

public class code7 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter a string1: ");
        String str1 = sc.nextLine();
        System.out.println("Enter a string2: ");
        String str2 = sc.nextLine();

        char res = newCharacter(str1 , str2);

        System.out.println("The new character is: " + res);
    }

    public static char newCharacter(String str1, String str2) {
        int sumStr1 = 0;
        int sumStr2 = 0;

        for(Character ch : str1.toCharArray()){
            sumStr1+=ch;
        }

        for(Character ch : str2.toCharArray()){
            sumStr2+=ch;
        }

        return (char) (sumStr2 - sumStr1);
    }
}
